import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["500"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mana.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased  `}>
      <body className={`${poppins.className} min-h-full  flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
